#!/bin/bash

set -e

ICINGA2_CONFDIR=/etc/icinga2
ICINGA2_DATADIR=/var/lib/icinga2

ensure_icinga_dir() {
  if [ ! -d "$1" ]; then
    mkdir "$1"
  fi
}

ensure_icinga_dir "${ICINGA2_CONFDIR}/zones.d"
ensure_icinga_dir "${ICINGA2_DATADIR}/api"
ensure_icinga_dir "${ICINGA2_DATADIR}/certs"

if [ "${ICINGA_NO_CONFIG}" != true ]; then
  icinga-docker-config
fi

exec "$@"
