#!/bin/bash

set -e

: "${ICINGA_NEW_FOREGROUND:=true}"

if [[ "$ICINGA_NEW_FOREGROUND" = true ]]; then
  echo "Starting Icinga 2 in foreground"
  icinga2 daemon
  exit 0
fi

echo "Using old foreground handling (ICINGA_NEW_FOREGROUND=false)"

rundir=/run/icinga2
pidfile="$rundir/icinga2.pid"

if ! /usr/sbin/icinga2 daemon -d "$@"; then
  echo "icinga2 failed to start!" >&2
  exit 1
fi

if [ ! -f "$pidfile" ]; then
  echo "PID file $pidfile does not exist!" >&2
  exit 1
fi

handleexit() {
  for _ in $(seq 1 10); do
    [ -f "$pidfile" ] || break
    pid="$(cat "$pidfile")"
    if kill -0 "$pid" &>/dev/null; then
      echo "Sending TERM to icinga2 ($pid)"
      kill "$pid"
      sleep 1
    fi
    break
  done
}

trap handleexit EXIT INT TERM

while [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; do
  # waiting as long as process lives
  sleep 1
done
